version: '3.7'
services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: localhost
    restart: always
    env_file:
      - app.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: Salman12
        MYSQL_DATABASE: restaurantmanagemensystem
    networks:
      - backend

  redis:
    image: redis:7.0.10
    container_name: redis
    restart: always
    env_file:
      - app.env
    ports:
      - "6379:6379"
    volumes:
      - rediscache:/data
    networks:
      - backend

  api_server:
    build: 
     context: .
    container_name: restaurantmanagementsystem
    restart: on-failure:5
    ports:
      - 4000:4000
    env_file:
      - app.env
    depends_on:
      - mysql
      - redis
    networks:
      - backend
    links:
      - mysql
      - redis
         
networks:
  backend:
   driver: bridge

volumes:
  mysql_data:
  rediscache:
   